server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

##scrape_configs:
##- job_name: pichula
##  static_configs:
##  - targets: 
##    - localhost
##    labels:
##      job: pichula
 ##     __path__: /var/log/*log

##scrape_configs:
##- job_name: 'myapp-logs'
##  static_configs:
##  - targets:
##    - localhost
 ##   labels:
 ##     job: "myapp-logs"
 ##     __path__: /var/log/myapp/*log